### ISSUE TITLE
Support for sigstore's protobuf bundle format coming from an OCI registry

### ISSUE THREAD

**Issue by rdimitrov** [mindersec/minder#2369]
Ensure/implement that Minder has support for provenance information stored in an OCI registry that uses the bundle format (currently it's only `simplesigning`).

References:
- https://github.com/sigstore/protobuf-specs/blob/b46b842040854ceab8f3a42547ae6e991793d0ef/protos/sigstore_bundle.proto#L111

**Comment by evankanderson** [comment]
We need a strategy for handling attestations more consistently in rules.  @puerco is thinking about this.

**Comment by evankanderson** [comment]
I think this will be obvious when we pick up artifact work again.  We've heard of sigstore somewhere...
