### ISSUE TITLE
Make homoglyph, vulnerability and Trusty check actions consistent when reviewing a PR

### ISSUE THREAD

**Issue by rdimitrov** [mindersec/minder#2529]
Currently we have a few rule types that act by parsing the contents of a PR - homoglyph, vulnerability and Trusty checks. Each parses the PR content and then comments/reviews or suggests an alternative dependency depending on the rule type. 

The issue is that Minder comments on a PR every time there's a change which eventually gets quite noisy for PRs that address feedback or continue to add changes.

There's already an effort which fixes this partially by simplifying and minimising the amount of comments done by Minder, but it's not working for all rule types. 

This issue is about fixing the differences and making this consistent across all rule types that act by commenting on a PR.

**Comment by evankanderson** [comment]
Do we have a list of the rule types (remediation types?) that don't follow our best practice pattern / library?
