### ISSUE TITLE
Switch from hardcoded default values to querying viper store for binding config flags

### ISSUE THREAD

**Issue by Vyom-Yadav** [mindersec/minder#3145]
The current pattern followed by our CLIs is as follows:

https://github.com/stacklok/minder/blob/17412a2b32338d4b7ac2b234efee3124e565f20d/internal/config/common.go#L84-L95

The default value of the flag is hardcoded. A better pattern would be to query the viper store for the flag value after setting the default values using:

https://github.com/stacklok/minder/blob/17412a2b32338d4b7ac2b234efee3124e565f20d/internal/config/utils.go#L201-L203

Something like:

```go
func RegisterReminderFlags(v *viper.Viper, flags *pflag.FlagSet) error {
	viperPath := "cursor_file"
	if err := config.BindConfigFlag(v, flags, viperPath, "cursor-file",
		v.GetString(viperPath), "DB Cursor file path for reminder", flags.String); err != nil {
		return err
	}
```

**Comment by evankanderson** [comment]
I think we did this somewhere along the way...
