### ISSUE TITLE
Trusty ruletype does not comment if it found a lower scored package but has no alternatives

### ISSUE THREAD

**Issue by jhrozek** [mindersec/minder#3164]
Apparently found during smoke testing

**Comment by evankanderson** [comment]
We should see if this is still true; I think I've seen this happen since.

**Comment by rdimitrov** [comment]
This is probably best to be done while refactoring the upcoming trusty/pr_vulnerability_check integration.

**Comment by evankanderson** [comment]
We're rewriting this rule and will introduce different bugs in the future.  Closing this one.

**Comment by rdimitrov** [comment]
hey, I think you forgot to close this one. I'll close it, but you can reopen it in case you had something else in mind 👍
