### ISSUE TITLE
Extend the Provider API with means of setting provider-specific values, to be called from the selector code

### ISSUE THREAD

**Issue by jhrozek** [mindersec/minder#3758]
The selector code will certain attributes such as is_fork, is_private or any custom key-value pairs from the provider. We need to define the provider interface and implement it.

**Comment by jhrozek** [comment]
This is no longer part of the selectors epic, but should be instead part of a new epic that we create for properties

**Comment by jhrozek** [comment]
CC @JAORMX for when you create the properties epic.

**Comment by evankanderson** [comment]
This got done!
