### ISSUE TITLE
EntityInfoWrapper.GetEntityDBIDs() hardcodes an architecture limitation

### ISSUE THREAD

**Issue by puerco** [mindersec/minder#3838]
The `EntityInfoWrapper.GetEntityDBIDs()` function returns UUIDs for three specific entity types: repo, artifact, and pull request:

https://github.com/stacklok/minder/blob/e77e1427679fc3b18111cfc565559dc661ab789f/internal/engine/entities/entity_event.go#L252-L255

To expand Minder in the future to handle other entity types we should replace this function and [all its invocations](https://github.com/search?q=repo%3Astacklok%2Fminder%20GetEntityDBIDs&type=code) with a more flexible alternative to work with any future entity.

**Comment by JAORMX** [comment]
Oh, this is accidentally being addressed. Yeah, assign it to me. Hopefully by the end of the week this will no longer be an issue.

**Comment by JAORMX** [comment]
this has been addressed and this function is no longer part of Minder.
