### ISSUE TITLE
Missing package alternatives when Minder comments on a PR

### ISSUE THREAD

**Issue by eleftherias** [mindersec/minder#4945]
### Describe the issue

When I have a profile that includes the Trusty ruletype
And I create a PR that adds a dependency
Then the Minder comment on the PR does not include package alternatives, even though Trusty does have alternatives for the specific package

Example comment on PR: https://github.com/eleftherias/demo-repo-python/pull/25#pullrequestreview-2429173373
The screenshot below shows the comment does not include alternatives.
<img width="933" alt="Screenshot 2024-11-12 at 11 36 24" src="https://github.com/user-attachments/assets/4c49dea2-63cd-4ec6-a866-9637413c1d59">

Note: I checked the Minder codebase and confirmed that the template still includes alternatives
https://github.com/mindersec/minder/blob/0c76dba40bd4dc9163730dc334136ae4c18889e3/internal/engine/eval/trusty/actions.go#L100-L109

**Comment by blkt** [comment]
[Here's](https://github.com/mindersec/minder/blob/657bf015e97b53d58cb057bc87420b31c4fbeeb7/internal/engine/eval/trusty/actions.go#L317-L329) the code related to this bug.

**Comment by blkt** [comment]
Solved by PR https://github.com/mindersec/minder/pull/5013
