### ISSUE TITLE
Duplicate key error when updating PR

### ISSUE THREAD

**Issue by eleftherias** [mindersec/minder#5139]
### Describe the issue

When I have a ruletype that applies to pull requests, and I create a pull request and then update it, I see the following error in minder-server:
```
error storing originating entity: pq: duplicate key value violates unique constraint \"entity_instances_project_id_provider_id_entity_type_name_key\"
```

Additional details:
```
{
  "level": "error",
  "messageStrategy": "toEntityInfoWrapper",
  "refreshStrategy": "addOriginatingEntityStrategy",
  "exception.message": "error storing originating entity: pq: duplicate key value violates unique constraint \"entity_instances_project_id_provider_id_entity_type_name_key\"",
  "caller": "github.com/mindersec/minder/internal/entities/handlers/handler.go:79",
  "Timestamp": 1733389945698836421,
  "message": "error refreshing entity"
}
```

### To Reproduce

1) Create a profile with the ruletype `mixed_scripts_check`.
2) Register a repository in Minder
3) Create a PR in the repository
4) Update the PR you created by changing a file

### What version are you using?

v0.0.77 and latest main

**Comment by JAORMX** [comment]
Interesting! We probably are issuing the wrong event type when getting a PR modification/update event from GH.
